# Generated by Django 3.2.6 on 2021-09-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alumnos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumnos',
        ),
    ]
